In [ ]:
import numpy as np
arr = np.array([1, 2, 3])
arr

array([1, 2, 3])

In [ ]:
type(arr)

numpy.ndarray

In [ ]:
arr.ndim # dimension

1

In [ ]:
np.arange(13, 19)  # print the range of values

array([13, 14, 15, 16, 17, 18])

In [ ]:
np.arange(13, 19, 2)

array([13, 15, 17])

In [ ]:
np.arange(13, 40, 4, dtype=float)

array([13., 17., 21., 25., 29., 33., 37.])

In [ ]:
# "linspace" divides the values into equal parts
np.linspace(0, 10, 5)

array([ 0. ,  2.5,  5. ,  7.5, 10. ])

In [ ]:
np.zeros(10),np.ones(10,dtype=int)

(array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]),
 array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1]))

In [ ]:
numbers = np.array([21,31,11,0,34,11])

In [ ]:
max(numbers)

34

In [ ]:
#argmax - position of the max value
#argmin - position of the min value
print(numbers.argmax())
print(numbers.argmin())

4
3


In [ ]:
#slicing and indexing
print(numbers[2])
numbers[2] = 100
numbers

11


array([ 21,  31, 100,   0,  34,  11])

In [ ]:
numbers[2:5], numbers[-4:]

(array([100,   0,  34]), array([100,   0,  34,  11]))

In [ ]:
_3d = np.array([[[1,2,3,4],[5,6,7,8],[2,4,6,8]]])
_3d

array([[[1, 2, 3, 4],
        [5, 6, 7, 8],
        [2, 4, 6, 8]]])

In [ ]:
_3d[0][1], _3d[0][1][3]

(array([5, 6, 7, 8]), 8)

In [ ]:
x = np.arange(18)
x

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17])

In [ ]:
#Reshape
x.reshape(3,6)

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [ ]:
np.random.rand(5)


array([0.68987273, 0.97960042, 0.83411151, 0.54927113, 0.71385561])

In [ ]:
np.random.randint(1,9)

7

In [ ]:
print(x)
x.sum()

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17]


153

In [ ]:
#sqrt & log
numbers = np.array([21,31,11,25,34,11])
print(np.sqrt(numbers))
print(np.log(numbers))
print(np.log10(numbers))

[4.58257569 5.56776436 3.31662479 5.         5.83095189 3.31662479]
[3.04452244 3.4339872  2.39789527 3.21887582 3.52636052 2.39789527]
[1.32221929 1.49136169 1.04139269 1.39794001 1.53147892 1.04139269]


In [ ]:
#absolute
np.abs(-5)

5